#! /usr/bin/env python3

import itertools
import numpy
import time

import mktl as mKTL

def test_callback(key, value, timestamp):
    print("%.3f: %s %s..." % (timestamp, key.name, repr(value)[:40]))

def main():
    item = mKTL.get('potpie.BULK')
    item.register(test_callback)

    while True:
        try:
            time.sleep(30)
        except (KeyboardInterrupt, SystemExit):
            break


if __name__ == '__main__':
    ##import cProfile
    ##cProfile.run('main()', 'testreqloop.profile')
    main()
